import '../../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { store } from '@store';
import { NextPage } from 'next';
import { DefaultLayout } from '@layout';

type NextPageWithLayout = NextPage & {
  Layout?: React.FunctionComponent;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const LayoutCustom = Component.Layout ?? DefaultLayout;

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <LayoutCustom>
          <Component {...pageProps} />
        </LayoutCustom>
      </Provider>
    </>
  );
}

export default MyApp;
